image: 
  - Visual Studio 2019
#  - macos 

#environment:
#  APPVEYOR_SAVE_CACHE_ON_ERROR: "true"

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11

platform: x64

install:
  - ps: Invoke-WebRequest https://github.com/csound/manual/archive/6.13.0.zip  -OutFile manual-src.zip
  - cmd: 7z x manual-src.zip
  - cmd: cd manual-6.13.0
  - ps: Invoke-WebRequest https://github.com/csound/csound/releases/download/6.13.0/Csound6.13.0_manual_html.zip -OutFile manual.zip
  - cmd: 7z x manual.zip 
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - ps: dir


cache:
  - C:\Users\appveyor\.m2

build_script:
  - cd manual
  - mvn compile
  - cd ..
  - cmd: mvn -P generate-manual -DCS_MANUAL_DIR=.\manual-6.13.0 install
  #- cd application
  #- mvn nbm:build-installers

artifacts:
  - path: application\target\blue*.zip
    name: Blue Zip 
    type: zip
  #- path: application\target\blue*macosx.tgz
  #  name: Blue MacOS 
  #- path: application\target\blue*windows.exe
  #  name: Blue Windows 
  #- path: application\target\blue*linux.sh
  #  name: Blue Linux 

