name: Blue CI Builds
on: push

jobs:
  build:
    runs-on: macOS-latest 
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '11' 

      - name: Build Blue Manual
        run: mvn compile 
        working-directory: ./manual

      - name: Build Blue 
        run: mvn -Pgenerate-manual,macOS clean install

      - uses: actions/upload-artifact@master
        with:
          name: Blue (Windows and Linux) 
          path: application/target/blue-2.8.0-SNAPSHOT.zip 
      - uses: actions/upload-artifact@master
        with:
          name: Blue (macOS .app)  
          path: application/target/blue_macOS_2.8.0-dev.zip 
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '11' 

      - name: Build Blue Manual
        run: mvn compile 
        working-directory: ./manual

      - name: Build Blue 
        run: mvn -Pgenerate-manual clean install -Dmaven.test.skip

      - uses: actions/upload-artifact@master
        with:
          name: Blue Linux Zip
          path: application/target/blue-2.8.0-SNAPSHOT.zip 

  build:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '11' 

      - name: Build Blue Manual
        run: mvn compile 
        working-directory: ./manual

      - name: Build Blue 
        run: mvn -Pgenerate-manual clean install -Dmaven.test.skip

      - uses: actions/upload-artifact@master
        with:
          name: Blue Windows Zip
          path: application/target/blue-2.8.0-SNAPSHOT.zip 
